<a href="https://colab.research.google.com/github/khushboo-2000/NumPy/blob/main/numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
# np.random.set_state((42,))
# np.random.seed(3)

In [ ]:
np.random.seed(42)

np.random.randn(2,3)

array([[ 0.49671415, -0.1382643 ,  0.64768854],
       [ 1.52302986, -0.23415337, -0.23413696]])

In [ ]:
np.random.seed(3)

np.random.randn(2,3)

array([[ 1.78862847,  0.43650985,  0.09649747],
       [-1.8634927 , -0.2773882 , -0.35475898]])

In [ ]:
np.random.randn(2,3)

array([[ 0.24196227, -1.91328024, -1.72491783],
       [-0.56228753, -1.01283112,  0.31424733]])

In [ ]:
np.random.randn(2,3)

array([[ 0.44792187, -0.99257899,  0.65956872],
       [-0.55382757,  0.06768433,  0.83691264]])

In [ ]:
np.random.randn(2,3)

array([[ 0.24196227, -1.91328024, -1.72491783],
       [-0.56228753, -1.01283112,  0.31424733]])

In [ ]:
r_s = np.random.RandomState(3)

In [ ]:
r_s.randn(2,3)

array([[ 0.98236743, -1.10106763, -1.18504653],
       [-0.2056499 ,  1.48614836,  0.23671627]])

In [ ]:
r_s.randn(2,3)

array([[-1.02378514, -0.7129932 ,  0.62524497],
       [-0.16051336, -0.76883635, -0.23003072]])

In [ ]:
a = np.arange(64)

In [ ]:
a = a.reshape(2,8,4)

In [ ]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47],
        [48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [ ]:
for i in a:
  # print(i)
  for j in i:
    # print(j)
    for k in j:
      print(k)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63


In [ ]:
a[0][3]

array([12, 13, 14, 15])

In [ ]:
a[0][0][2]

2

In [ ]:
a[1][4][-1]

51

In [ ]:
a[0][5][1][1]

23

In [ ]:
a.ndim

4

In [ ]:
a = np.array([[10,20,30],
              [40,50,60],
              [70,80,90]
              
])

In [ ]:
a

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [ ]:
a[0]

array([10, 20, 30])

In [ ]:
a[:3,1]

array([20, 50, 80])

In [ ]:
a[0:, 1:2]

array([[20],
       [50],
       [80]])

In [ ]:
a[1:2, -1]

array([60])

In [ ]:
a[:1, 1:]

array([[20, 30]])

In [ ]:
b = [1,2,3,4,5]

In [ ]:
b[:4]

[1, 2, 3, 4]

In [ ]:
a

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [ ]:
mask = ~(a > 40)
mask

array([[ True,  True,  True],
       [ True, False, False],
       [False, False, False]])

In [ ]:
a[a>40]

array([50, 60, 70, 80, 90])

In [ ]:
a[mask]

array([10, 20, 30, 40])

In [ ]:
np.mean(a)

50.0

In [ ]:
np.mode(a)

AttributeError: ignored

In [ ]:
a = np.array([
    [1,2,3],
    [4,5,6]
])
b = np.array([
    [7,8,9],
    [10,11,12]
])

In [ ]:
a, b

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]]))

In [ ]:
a.shape, b.shape

((2, 3), (2, 3))

In [ ]:
a.dot(b)

ValueError: ignored

In [ ]:
b.T

array([[ 7, 10],
       [ 8, 11],
       [ 9, 12]])

In [ ]:
np.transpose(b)

array([[ 7, 10],
       [ 8, 11],
       [ 9, 12]])

In [ ]:
b.reshape(3,2)

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [ ]:
a.T.dot(b)

array([[47, 52, 57],
       [64, 71, 78],
       [81, 90, 99]])

In [ ]:
a.dot(b.T)

array([[ 50,  68],
       [122, 167]])

In [ ]:
np.dot(a, b.T)

array([[ 50,  68],
       [122, 167]])

In [ ]:
np.matmul(a,b.T)

array([[ 50,  68],
       [122, 167]])

In [ ]:
a.dot(b.reshape(3,2))

array([[ 58,  64],
       [139, 154]])

In [ ]:
a = np.array([
    [1,2,3],
    [4,5,6]
])

b = np.array([
    [7,8,9],
    [10,11,12],
    [13,14,15]
])

In [ ]:
a.shape, b.shape

((2, 3), (2, 3))

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
b

array([[ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [ ]:
np.concatenate([a,b], axis = 0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [ ]:
np.stack([a,b])

In [ ]:
import numpy as np

In [ ]:
a = np.arange(16)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
a = a.reshape(4,2,2)

In [ ]:
a

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]]])

In [ ]:
a.sum(axis = 0)

array([[24, 28],
       [32, 36]])

In [ ]:
a.sum(axis = 1)

array([[ 2,  4],
       [10, 12],
       [18, 20],
       [26, 28]])

In [ ]:
a.sum(axis = 2)

array([[ 1,  5],
       [ 9, 13],
       [17, 21],
       [25, 29]])